# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2fc12fae339fb3a69ecd79b7c4db81d5537a089aede8263b1e17181f856f2139d3b1d8e248658eaf665fb528205a3db0cc44e7659c9a815dfaadc5a4616b6911

test:
  secret_key_base: 5f7d3101fce330e08974879575635b8b2328e08e9313fca9ad8609739fbd1a4a83b968324de1262aeb1a0112f8f5e776fd0bab1f61840c0c7037365d74b85b26

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
